### PR TITLE
Add support for Cloudinary CDN

### PR DESCRIPTION
**Pull request by kiliman**
Includes the following new settings:

* markdown-image.cloudinary.cloudName
* markdown-image.cloudinary.apiKey
* markdown-image.cloudinary.apiSecret
* markdown-image.cloudinary.folder

I also updated the README and CHANGELOG but did not assign a version, since I'm not sure how you prefer to version this extension.

### CODE REVIEW

**Comment by kiliman** [comment]
Sorry about the whitespace changes. My editor is set to strip all trailing whitespaces, and my diff viewer ignores whitespace diffs, so I didn't see those. Let me know if that's an issue.

**Comment by imlinhanchao** [comment]
> Sorry about the whitespace changes. My editor is set to strip all trailing whitespaces, and my diff viewer ignores whitespace diffs, so I didn't see those. Let me know if that's an issue.

That' all right. I'll merge and then fix it.

**Comment by imlinhanchao** [comment]
I have a question.

Can Cloudinary customize the saved file name? Because the extension provides a `fileformat` option, the user can generate a file name and save path based on variables. That is the `savePath` variable of the `upload` function. I just found out that you did not use the variable `savePath`.

**Comment by kiliman** [comment]
I’ll take a look at the API and send another PR if possible. Thanks!

**Comment by imlinhanchao** [comment]
I was publish this verion to market first. If you find the way to customize  file name.  You can send another PR. Tks.

**Pull request merged**
